version: "3"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: BrainGames
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bee561333
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lumalab-network

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB_NAME=BrainGames
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=bee561333
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5433
    networks:
      - lumalab-network

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - lumalab-network

networks:
  lumalab-network:
    driver: bridge

volumes:
  postgres_data:
