version: "3"

services:

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "8001:8000"
    container_name: bgdjango_container
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3001:3000"
    container_name: bgreact_container
    depends_on:
      - backend

  db:
    image: postgres
    environment:
      POSTGRES_DB: BrainGames
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bee561333
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: bgpostgres_container
    restart: always
    ports:
      - "5433:5432"

volumes:
  postgres_data:
